# GoEdu Control Testing Platform Configuration
# This file contains the default configuration for the application.
# Override these settings using environment variables in production.

app:
  name: "GoEdu Control Testing Platform"
  version: "1.0.0"
  environment: "development"
  port: 8080
  host: "0.0.0.0"
  timeout: "30s"
  cors:
    allowed_origins:
      - "http://localhost:3000"
      - "http://localhost:3001"
    allowed_methods:
      - "GET"
      - "POST" 
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed_headers:
      - "Authorization"
      - "Content-Type"
      - "X-Correlation-ID"

database:
  uri: "mongodb://localhost:27017"
  database: "goedu"
  max_pool_size: 100
  min_pool_size: 10
  max_conn_idle_time: "5m"
  connect_timeout: "10s"
  server_select_timeout: "10s"

cache:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  max_retries: 3
  pool_size: 10
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  idle_timeout: "5m"

storage:
  endpoint: "localhost:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  bucket_name: "goedu-evidence"
  region: "us-east-1"
  use_ssl: false

auth:
  jwt_secret: "your-secret-key-change-in-production"
  jwt_expiration: "24h"
  bcrypt_cost: 12
  oauth_provider: ""
  oauth_client_id: ""
  oauth_client_secret: ""
  oauth_redirect_url: ""

logger:
  level: "debug"
  environment: "development"
  output_path: "stdout"

email:
  provider: "smtp"
  api_key: ""
  from: "noreply@goedu.com"
  smtp_host: "localhost"
  smtp_port: 587
  smtp_username: ""
  smtp_password: ""

webhook:
  secret: ""
  timeout: "30s"
  retry_count: 3
  retry_delay: "5s"

monitoring:
  enabled: true
  metrics_path: "/metrics"
  health_check_path: "/health"
  prometheus_enabled: true